# Generated by Django 4.1.7 on 2023-07-21 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cliente_idade_alter_cliente_nascionalidade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
