# Generated by Django 4.1.7 on 2023-07-21 00:52

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(default=django.utils.timezone.now, verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome_completo', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='Sexo')),
                ('nascimento', models.DateField(default=datetime.date.today, verbose_name='Data de Nascimento')),
                ('nascionalidade', models.CharField(default='Brasileira', max_length=10, verbose_name='Nascionalidade')),
                ('nome_pai', models.CharField(max_length=100, verbose_name='Nome do Pai')),
                ('nome_mae', models.CharField(max_length=100, verbose_name='Nome da Mãe')),
                ('cor', models.CharField(choices=[('N', 'Negro'), ('B', 'Branco'), ('I', 'Índigena'), ('A', 'Amarela'), ('P', 'Pardo')], default='Negro', max_length=1, verbose_name='Cor/Raça')),
                ('religião', models.CharField(max_length=50, verbose_name='Religião')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
