# Generated by Django 4.1.7 on 2023-07-21 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='religião',
            new_name='religion',
        ),
    ]
