# Generated by Django 4.1.7 on 2023-07-21 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_religião_cliente_religion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='criado',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='modificado',
        ),
    ]
