# Generated by Django 4.1.7 on 2023-07-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_cliente_ativo_remove_cliente_criado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
    ]
