# Generated by Django 4.1.7 on 2023-07-22 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_cliente_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
    ]
